package com.compliance.verificationservice.enums;

public enum VerificationAuditAction {

    VERIFICATION_REQUESTED,
    VERIFICATION_STARTED,
    VERIFICATION_COMPLETED,
    VERIFICATION_FAILED,

    VERIFICATION_RETRY_REQUESTED,
    VERIFICATION_RETRY_COMPLETED,
    VERIFICATION_RETRY_FAILED,

    VERIFICATION_RESULT_VIEWED,
    VERIFICATION_LATEST_RESULT_VIEWED,
    VERIFICATION_HISTORY_VIEWED,
    VERIFICATION_RESULTS_LISTED,
    VERIFICATION_RESULTS_FILTERED,
    VERIFICATION_USER_RESULTS_VIEWED,
    VERIFICATION_SUMMARY_VIEWED,

    MANUAL_REVIEW_REQUESTED,
    MANUAL_REVIEW_APPROVED,
    MANUAL_REVIEW_REJECTED,
    MANUAL_REVIEW_RETURNED_FOR_REPROCESSING,

    OCR_COMPLETED_EVENT_RECEIVED,
    OCR_COMPLETED_EVENT_PROCESSED,
    OCR_COMPLETED_EVENT_FAILED
}