package com.compliance.documentservice.enums;

public enum AuditActionType {

    DOCUMENT_UPLOADED,
    DOCUMENT_VIEWED,
    DOCUMENT_LIST_VIEWED,
    USER_DOCUMENTS_VIEWED,
    DOCUMENT_DOWNLOADED,
    DOCUMENT_UPDATED,
    DOCUMENT_STATUS_CHANGED,
    DOCUMENT_DELETED,
    DOCUMENT_UPLOAD_FAILED,
    DOCUMENT_DOWNLOAD_FAILED
}