package com.compliance.ocrservice.enums;

public enum OcrAuditAction {

    OCR_PROCESS_REQUESTED,
    OCR_PROCESS_COMPLETED,
    OCR_PROCESS_FAILED,

    OCR_RETRY_REQUESTED,
    OCR_RETRY_COMPLETED,
    OCR_RETRY_FAILED,

    OCR_RESULT_VIEWED,
    OCR_LATEST_RESULT_VIEWED,
    OCR_HISTORY_VIEWED,
    OCR_USER_RESULTS_VIEWED,
    OCR_RESULTS_FILTERED,
    OCR_RESULTS_LISTED,
    OCR_SUMMARY_VIEWED,

    DOCUMENT_UPLOAD_EVENT_RECEIVED,
    DOCUMENT_UPLOAD_EVENT_COMPLETED,
    DOCUMENT_UPLOAD_EVENT_FAILED
}